{% set name = "html5lib-modern" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/html5lib_modern-{{ version }}.tar.gz
  sha256: 1fadbfc27ea955431270e4e79a4a4c290ba11c3a3098a95cc22dc73e312a1768

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8

test:
  imports:
    - html5lib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ashleysommer/html5lib-modern
  summary: Python 3 version of html5lib-python HTML parser based on the WHATWG HTML specification
  license: MIT
  license_file:
    - LICENSE
    - html5lib/tests/testdata/LICENSE
  description: |
    Python 3 version of the standards-compliant library for parsing and serializing HTML documents and fragments in Python.
    This is a fork of the html5lib project https://github.com/html5lib/html5lib-python
    with the intention to make this new release available for users without the overhead of python2.7 support, or the dependency on the six library.
    This release is a snapshot of the v1.2-dev codebase plus the addition of the "remove python 2.7" work and the "remove six" work. This version of html5lib works only on Python 3.8 and newer.

extra:
  recipe-maintainers:
    - rxm7706
